# Generated by Django 3.1.3 on 2020-11-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='会话开始时间')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.URLField()),
                ('profile', models.CharField(default='', max_length=200, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', '男'), ('M', '女')], default='F', max_length=2)),
                ('tel_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('icon', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.BigIntegerField(choices=[(1, 'text'), (2, 'files')])),
                ('content', models.CharField(max_length=200)),
                ('chat_id', models.ManyToManyField(related_name='user_messages', to='chat.chat', verbose_name='接收到的用户信息')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_messages', to='chat.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_messages', to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='userGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('message_set', models.BigIntegerField(choices=[(1, '接收并提醒'), (2, '接收但不提醒'), (3, '接收但不提醒'), (4, '屏蔽群消息')], default=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('chat_background_img', models.URLField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='chat.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='groupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.BigIntegerField(choices=[(1, 'text'), (2, 'files')])),
                ('content', models.CharField(max_length=200)),
                ('chat_id', models.ManyToManyField(related_name='group_messages', to='chat.chat', verbose_name='接收到的群组信息')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMessage_set', to='chat.group', verbose_name='接收的群')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user', verbose_name='发送人')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=40)),
                ('login_time', models.DateTimeField(verbose_name='date_login')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts_set', to='chat.user', verbose_name='所属用户'),
        ),
    ]
