# Generated by Django 3.1.3 on 2020-11-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', '男'), ('M', '女')], default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel_number',
            field=models.CharField(default=12345678901, max_length=11),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='user_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=40)),
                ('login_time', models.DateTimeField(verbose_name='date_login')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
    ]
