# Generated by Django 3.1.3 on 2020-11-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201121_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='会话开始时间')),
            ],
        ),
        migrations.CreateModel(
            name='groupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.BigIntegerField(choices=[(1, 'text'), (2, 'files')])),
                ('content', models.CharField(max_length=200)),
                ('chat_id', models.ManyToManyField(related_name='group_messages', to='chat.chat', verbose_name='接收到的群组信息')),
            ],
        ),
        migrations.CreateModel(
            name='userGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('message_set', models.BigIntegerField(choices=[(1, '接收并提醒'), (2, '接收但不提醒'), (3, '接收但不提醒'), (4, '屏蔽群消息')], default=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('chat_background_img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.BigIntegerField(choices=[(1, 'text'), (2, 'files')])),
                ('content', models.CharField(max_length=200)),
                ('chat_id', models.ManyToManyField(related_name='user_messages', to='chat.chat', verbose_name='接收到的用户信息')),
            ],
        ),
        migrations.RenameModel(
            old_name='clients',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='user_group',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_messages', to='chat.user'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_messages', to='chat.user'),
        ),
        migrations.AddField(
            model_name='usergrouprelation',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='chat.group'),
        ),
        migrations.AddField(
            model_name='usergrouprelation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='chat.user'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMessage_set', to='chat.group', verbose_name='接收的群'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user', verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts_set', to='chat.user', verbose_name='所属用户'),
        ),
    ]
